name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        avx: ["disabled", "enabled"]

    name: "Build & Test (avx: ${{ matrix.avx }})"

    steps:
      - uses: actions/checkout@v4
      - name: Set RUSTFLAGS
        run: |
          if [ "${{ matrix.ssse3 }}" = "disabled" ]; then
            echo "RUSTFLAGS=-C target-feature=-avx2" >> $GITHUB_ENV
          else
            echo "RUSTFLAGS=-C target-feature=+avx2" >> $GITHUB_ENV
          fi
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test -- --include-ignored
